### ISSUE TITLE
[BUG][NOWEB] -get group error  /api/session/groups/xxx@g.us

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#462]
/api/session/groups/xxx@g.us
{
  "statusCode": 500,
  "timestamp": "2024-07-30T09:56:20.647Z",
  "exception": {
    "stack": "Error: rate-overlimit\n    at assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:145:48)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.groupFetchAllParticipating (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:26:24)\n    at async WhatsappSessionNoWebPlus.getGroup (/app/dist/core/engines/noweb/session.noweb.core.js:521:24)",
    "message": "rate-overlimit",
    "data": 429,
    "isBoom": true,
    "isServer": true,
    "output": {},
    "name": "Error"
  },
  "request": {
    "path": "/api/TCN013/groups/120363298657503778%40g.us",
    "method": "GET",
    "body": {},
    "query": {}
  },
  "version": {
    "version": "2024.7.6",
    "engine": "NOWEB",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by HuangDaHui** [comment]
Just delete the session and recreate it
But this affects the use because you need to re-scan the QRcode after deletion.

**Comment by devlikepro** [comment]
Hi! How frequently you request the endpoint?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
Hi, actually my requests are not frequent. This error will also appear when I test the interface directly in swagger.

**Comment by masitings** [comment]
Im facing the same issue aswell. Basically, what i do is just keep requesting the groups and added the channel to the group that other account's who created it. But my case is when i trigger it directly in swagger, its ok no error. But when i use my application to hit the api, it give me 500

<img width="385" alt="image" src="https://github.com/user-attachments/assets/9f033e39-cb1a-48aa-bae0-0d569dfd747b">

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by LucasEduard0** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by melquisedeque-magalhaes** [comment]
+1

**Comment by lucas-cassiano** [comment]
+1

**Comment by devlikepro** [comment]
Hi! Fixed in `2024.12.3`
Remember to [**Enable NOWEB Store**](https://waha.devlike.pro/docs/engines/noweb/#enable--store) for the optimization!

Added dedicated [**POST /api/{session}/groups/refresh**](https://waha.devlike.pro/docs/how-to/groups/#refresh-groups) to force refresh group list from the server if you see any inconsistency in groups or participants

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Vaibhav1104** [comment]
@devlikepro i am getting this issue, i have tried refresh but still that is also giving 502. Is there any solution ??
```
{
  "statusCode": 500,
  "timestamp": "2026-06-15T10:00:18.609Z",
  "exception": {
    "message": "async-lock timed out in queue groups-fetch",
    "name": "Error",
    "stack": "Error: async-lock timed out in queue groups-fetch\n    at Timeout._onTimeout (/app/node_modules/async-lock/lib/index.js:213:17)\n    at listOnTimeout (node:internal/timers:605:17)\n    at process.processTimers (node:internal/timers:541:7)"                                                                                                                                       
  },
  "request": {
    "path": "/api/TWC_TECH/groups/refresh",
    "method": "POST",
    "body": {},
    "query": {}
  },
  "version": {
    "version": "2026.5.1",
    "engine": "NOWEB",
    "tier": "PLUS",
    "browser": null,
    "platform": "linux/x64",
    "worker": {
      "id": null
    }
  }

```
```
curl -s -H "X-Api-Key: $WAHA_API_KEY" \
    "$WAHA_BASE_URL/api/$WAHA_SESSION/groups/xxx%40g.us"
{
```
Response : 
```
{
  "statusCode": 500,
  "timestamp": "2026-06-15T09:49:32.030Z",
  "exception": {
    "message": "internal-server-error",
    "data": 500,
    "isBoom": true,
    "isServer": true,
    "output": {},
    "name": "Error",
    "stack": "Error: internal-server-error\n    at assertNodeErrorFree (file:///app/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:57:15)\n    at query (file:///app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)\n    at async Object.groupFetchAllParticipating (file:///app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:24:24)\n    at async /app/dist/core/engines/noweb/store/NowebPersistentStore.js:461:13"                                                  
  },
  "request": {
    "path": "/api/XXX/groups/xxx%40g.us",
    "method": "GET",
    "query": {}
  },
  "version": {
    "version": "2026.5.1",
    "engine": "NOWEB",
    "tier": "PLUS",
    "browser": null,
    "platform": "linux/x64",
    "worker": {
      "id": null
    }
  }
}
```

**Comment by Vaibhav1104** [comment]
i found that solution is session restart , but is there any better solution ? @devlikepro

**Comment by Vaibhav1104** [comment]
Hello devlikepro , i am still getting this error. Please let me know how to resolve this issue @devlikepro 
@LucasEduard0 @HuangDaHui if you have any solution then please share , Thanks
